users_name_max_length: 50
users_email_max_length: 255
users_password_min_length: 6
gravatar_size: 50
default_gravatar_size: 50
users_per_page: 25
reset_token_duration: 2
maximum_post_length: 140
default_pic_width: 400
default_pic_height: 400
max_file_size: 5
stats_gravatar_size: 30
